### PR TITLE
Added Parks API test

### PR DESCRIPTION
**Pull request by blusanders**
Added parks provider and a call to ParksList in main.js to test parks API

Fixes # (issue)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

git fetch --all
git checkout bs-holiday-first

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by AndreaMays — DISMISSED** [review]
Looks great! Thanks for the API testing

**Review by Loganwebb1994 — DISMISSED** [review]
👍

**Review by powellmad — APPROVED** [review]
Pulled this branch down and everything looks good!

**Review by AndreaMays — APPROVED** [review]

**Review by Loganwebb1994 — APPROVED** [review]
:)

**Pull request merged**
