### PR TITLE
Mp weather provider

### PR DESCRIPTION
**Pull request by powellmad**
# Description

Built out the weather forecast modules and added initial styling to weather cards

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

Please check that the weather shows up in the DOM and there are no errors in the console.

```
git fetch --all
git checkout mp-weather-prov
```

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Loganwebb1994 — COMMENTED** [review]
Need to remove "J" from line 9 of main.js

**Review by blusanders — APPROVED** [review]
Weather renders properly

**Review by Loganwebb1994 — APPROVED** [review]
👍

**Review by AndreaMays — APPROVED** [review]
looks good

**Review by blusanders — APPROVED** [review]
Code still looks good. Thank God.

**Pull request merged**
